### ISSUE TITLE
Release for hydro and indigo

### ISSUE THREAD

**Issue by dlaz** [DLu/wu_ros_tools#5]
Could we get a release for hydro and indigo with the changes since 0.2.3?

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/8907

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/8908

**Comment by dlaz** [comment]
Thank you!

**Comment by DLu** [comment]
No problem Jade for no additional cost: https://github.com/ros/rosdistro/pull/8909
