### ISSUE TITLE
Please make new releases for packaging.

### ISSUE THREAD

**Issue by bionade24** [DLu/wu_ros_tools#7]
Hi, I'm one of the ROS melodic AUR maintainers and your latest release is pretty old. It would be nice if we could get a newer tarball.

**Comment by DLu** [comment]
Why did you close this?

**Comment by bionade24** [comment]
Because it's also fine using tags. I just overviewed them first, because they're minimized as default.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/24308
